services:
  # ─── MySQL Database ───
  mysql:
    image: mysql:8.0
    container_name: fintrack-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: finance_manager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─── Spring Boot Backend ───
  backend:
    build: ./backend
    container_name: fintrack-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/finance_manager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      APP_JWT_SECRET: ${JWT_SECRET:-8f4b2c9e1a3d7f6e0b5c8a2d4e6f1a3b5c7d9e0f2a4b6c8d0e1f3a5b7c9d1e}
      APP_JWT_EXPIRATION_MS: 86400000
      APP_CORS_ALLOWED_ORIGINS: http://13.62.228.49:3000  #replace localhost by the ip of the ec2 
    depends_on:
      mysql:
        condition: service_healthy
x   
  # ─── React Frontend (Nginx) ───
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://13.62.228.49:8080/api #replace localhost by the ip of the ec2 
    container_name: fintrack-frontend
    restart: unless-stopped
    ports:
      - "3000:80"     # 80 port here note 
    depends_on:
      - backend

volumes:
  mysql_data:
